export const ActionTypes = {
  REQUEST_INVITE_LOADING: 'REQUEST_INVITE_LOADING',
  REQUEST_INVITE_SUCCESS: 'REQUEST_INVITE_SUCCESS',
  REQUEST_INVITE_FAIL: 'REQUEST_INVITE_FAIL',
  RESET_DIALOG_STATUS: 'RESET_DIALOG_STATUS',
  HOME_SHOW_REQUEST_INVITE_DIALOG: 'HOME_SHOW_REQUEST_INVITE_DIALOG',
  HOME_DISMISS_REQUEST_INVITE_DIALOG: 'HOME_DISMISS_REQUEST_INVITE_DIALOG'
}