export const ActionTypes = {
  REQUEST_INVITE_LOADING: Symbol(),
  REQUEST_INVITE_SUCCESS: Symbol(),
  REQUEST_INVITE_FAIL: Symbol(),
  RESET_DIALOG_STATUS: Symbol(),
  HOME_SHOW_REQUEST_INVITE_DIALOG: Symbol(),
  HOME_DISMISS_REQUEST_INVITE_DIALOG: Symbol()
}